### ISSUE TITLE
Support of Laravel 6+

### ISSUE THREAD

**Issue by kadirovazizbek** [GooGee/Entity#1]
Is Laravel 6+ supported? I'm using Laravel 6. When I install Entity 2.4 and latest Entity Builder, localhost/dist gives me blank page.

**Comment by GooGee** [comment]
Make sure this file exists &lt;Laravel project&gt;/public/dist/index.html

**Comment by shabeebrizvi** [comment]
FYI, I am able to run Entity Builder v6.0.0 with PHP package Entity v2.2.1 on Laravel 8. It works just fine but ran into some data split version mismatch error with Entity v2.3.0.
